version: "0.1"

services:
  water_rights_visualizer:
    build: .
    container_name: water-rights-visualizer
    restart: always
    command: "npm run ${WATER_RIGHTS_SOURCE:-S3}"
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
