version: "0.1"

services:
  water_rights_visualizer:
    build: .
    container_name: water-rights-visualizer
    restart: always
    ports:
      - "8000:8000"
    command: "npm run ${WATER_RIGHTS_SOURCE:-S3}"
