name: Bump Package Version on Merge

on:
  push:
    branches:
      - main
      - develop

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        working-directory: ./client
        run: yarn install

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Determine Version Bump Type
        id: version_type
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "version_type=minor" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "version_type=patch" >> $GITHUB_OUTPUT
          fi

      - name: Bump Version
        working-directory: ./client
        run: npm version ${{ steps.version_type.outputs.version_type }} -m "Bump version to %s [skip ci]"

      - name: Push Changes
        run: |
          git add client/package.json
          git commit -m "Bump version [skip ci]"
          git push origin ${{ github.ref_name }}
